### ISSUE TITLE
add icons

### ISSUE THREAD

**Issue by LRvdLinden** [menahishayan/HomeAssistant-Cupertino-Icons#1]
Please add Copyrighted icons excluded and show a link to Apple disclaimers. Need appletv icons

**Comment by menahishayan** [comment]
Firstly, exporting, converting and reusing those icons in a non-Apple-approved app would be a legal violation of Apple's terms of use for these icons.

Second, Apple's SF Symbols Viewer blocks users from exporting copyrighted icons, so I couldn't get my hands on the original files for those icons.
