### ISSUE TITLE
How do you use multicolor icons?

### ISSUE THREAD

**Issue by grischard** [menahishayan/HomeAssistant-Cupertino-Icons#11]
Using `ios:gear-badge-xmark#fullcolor` like in the README gives me a coloured icon, but `ios:ladybug-fill#fullcolor` remains black. Have others been successful in using multicolor icons?

**Comment by grischard** [comment]
Duplicate of #9

**Comment by JEugenio-GitHub** [comment]
The same thing is happening for me, I have tried multiple icons that are included in the "supported list" in the duplicate bug linked above.
