### ISSUE TITLE
Update icons to SF Symbols v3

### ISSUE THREAD

**Issue by yonigold1** [menahishayan/HomeAssistant-Cupertino-Icons#2]
Hey i was just wondering if you could add the new icons in sf symbols 3. Also if possible add the apple devices as i have an entity for my iPhone and mac and would love to use the SF Symbol for it :)

Thanks so much for this repo :))))

**Comment by menahishayan** [comment]
SF Symbols have been updated to v3.0!

> if possible add the apple devices

Sorry, those icons are copyrighted and we're not legally allowed to add/use them
