### ISSUE TITLE
Icons not loading on fresh load. 

### ISSUE THREAD

**Issue by squk** [menahishayan/HomeAssistant-Cupertino-Icons#3]
To reproduce: 
 - Set an icon as your views(tab) icon
 - Reload HA from a different device
 - Icons will not load until you go into the edit dashboard view

**Comment by menahishayan** [comment]
Custom icons for HA merely provide the icons alone. There is no code here pertaining to when and how these icons are fetched/loaded. This sounds like a bug in HomeAssistant's frontend. You can open a PR here: [https://github.com/home-assistant/frontend](https://github.com/home-assistant/frontend)
