### ISSUE TITLE
Enlarges Hass Hue Icons when installed

### ISSUE THREAD

**Issue by gvssr** [menahishayan/HomeAssistant-Cupertino-Icons#4]
For some reason, when installing this integration, it enlarges any used Hass Hue Icons on Lovelace:

![image](https://user-images.githubusercontent.com/61377476/140605111-5dcc2942-a82e-47ba-ab53-8720001de478.png)

**Comment by menahishayan** [comment]
These custom components don't communicate with each other, and there's no code on here that would cause **any** icon to change size, irrespective of source. It could either be a bug in HACS or Lovelace/ HA 2021.11.

What I would suggest:
 - Reset the frontend cache from Lovelace/HACS
 - Reset the  frontend cache from the iOS/macOS apps
 - Restart Home Assistant
 - Try logging in from the browser in private browsing mode

Additionally, to get more insights on the issue, uninstall one of the integrations / disable any one of the integrations and repeat the above steps to see if the order of loading has any effect on this bug.

**Comment by gvssr** [comment]
Hi, I was in the process of removing Hass Hue Icons and change the install order when I noticed the Cupertino icons don't actually seem to load in, even with Hue Icons still uninstalled. Tried rebooting HA, resetting front-end cache en mobile cache, even rebooting the host: ![image](https://user-images.githubusercontent.com/61377476/140608481-dd900226-36db-45ee-b0d2-ee586b41c2a9.png)

**Comment by gvssr** [comment]
Some more testing: while they don't show up in the icon picker, they do show up when selected. However, like with Hass Hue Icons (when it was installed together with this integration) they show up as huge:
![image](https://user-images.githubusercontent.com/61377476/140608790-0ec8c0fd-6a00-48ea-a9ca-6fd065a049f1.jpeg)

Even when opening an entity:
![image](https://user-images.githubusercontent.com/61377476/140608795-bfe87116-2ff7-4728-b044-0a065357f0ba.jpeg)

**Comment by gazpachoking** [comment]
Having the same problem. As soon as I added this integration, the HACS icon got huge. Uninstalling this integration returned it to the normal size.
![image](https://user-images.githubusercontent.com/187133/140985314-e316c017-3b0c-4095-8f33-2884f93c93c0.png)

**Comment by filikun** [comment]
For me the cupertino icons is big as well. Only the original mdi icons are the right size.

**Comment by gvssr** [comment]
@menahishayan Looks like fontawesome was having the same issue and they fixed it: https://github.com/thomasloven/hass-fontawesome/releases/tag/2.1.5

The specific commit: https://github.com/thomasloven/hass-fontawesome/commit/cb7b171e9cc0f54729d4dd69446a434267db0169

**Comment by ErilovNikita** [comment]
> Anybody found a fix for this?
If you want to use Cupertino Icons here is my repo, here I adjusted the sizes and now everything looks good
[ErilovNikita/HomeAssistant-Cupertino-Icons](https://github.com/ErilovNikita/HomeAssistant-Cupertino-Icons.git)

**Comment by gvssr** [comment]
@ErilovNikita your repo worked for me, thank you!

**Comment by gvssr** [comment]
Just as a follow up, as confirmed by @ErilovNikita’s fork and [this comment](https://github.com/arallsopp/hass-hue-icons/issues/109#issuecomment-985641315) it’s up to the integration owner to fix this issue.

@menahishayan have you had time to look at the above example? Maybe @ErilovNikita can create a pull request.

**Comment by menahishayan** [comment]
@gvssr thanks for pointing it out! @ErilovNikita thank you for contributing! Please open a pull request so we can merge the solution.

**Comment by menahishayan** [comment]
> @menahishayan Looks like fontawesome was having the same issue and they fixed it: https://github.com/thomasloven/hass-fontawesome/releases/tag/2.1.5
> 
> The specific commit: [thomasloven/hass-fontawesome@cb7b171](https://github.com/thomasloven/hass-fontawesome/commit/cb7b171e9cc0f54729d4dd69446a434267db0169)

@gvssr I've added changes based on the commit you linked. Please update to v3.0.2 and let me know if it's resolved.

**Comment by gvssr** [comment]
@menahishayan Just updated and tested, looks good. Thanks! Closing this issue.
