### ISSUE TITLE
Icons are not available

### ISSUE THREAD

**Issue by cpaucar3** [menahishayan/HomeAssistant-Cupertino-Icons#5]
I'm running the latest HA core container. I installed the v3.0.1 integration via HACS for the first time yesterday. I reinstalled it today. I rebooted my computer. Afterwards I logged into my dashboard in private mode in my browser. I still cannot see the new icons, and when I copy/paste the new icon text string it doesn't even show up on the lovelace card.

**Comment by mkgreco** [comment]
Same problem here - tried the same steps, but no ios prefixed icons are showing up whatsoever

**Comment by YMGV** [comment]
same problem here - only as a new user

**Comment by dieantu** [comment]
Same issue. installed v3.0.1 with HACS. HAS version  2021.11.1

**Comment by ElVit** [comment]
Same problem here. 
![image](https://user-images.githubusercontent.com/54866762/140658001-7e857d76-a454-4d5c-ba82-6cc263432224.jpeg)

**Comment by ElVit** [comment]
Sorry didn't read the instruction carefully enough. The hacs repo had to be added as an "integration". 
Now I have added the repo, installed the integration and restarted Home Assistant. I can also choose the icons in the icon picker, but I cannot see the images. 
![image](https://user-images.githubusercontent.com/54866762/140660039-7f170921-5226-454f-ac85-4ab12dcad3f3.jpeg)

**Comment by ElVit** [comment]
Ok sorry for the third post in such short time. It seems that the image is not shown in the icon picker and also is not working as a lovelace tab icon. 
But it is working on a lovelace card e.g. the entities card. But as in issue #4 was told the icon size is too big.

**Comment by masto** [comment]
I have the same problem **in Safari** (Version 14.1.2 (16611.3.10.1.6)), but it works in Chrome. Poking around with the web inspector, it seems like the Cupertino icons are getting a width of 0 in the icon picker. If I edit that to 24, they display. But that's about where my frontend skills end. I couldn't figure out where this is supposed to be set or why it's not working.

<img width="1571" alt="Screen Shot 2021-11-07 at 5 30 28 PM" src="https://user-images.githubusercontent.com/645516/140664270-1f3e7b2e-4c08-4a22-bf02-b73e18d943ad.png">

**Comment by menahishayan** [comment]
> I have the same problem **in Safari** (Version 14.1.2 (16611.3.10.1.6)), but it works in Chrome. Poking around with the web inspector, it seems like the Cupertino icons are getting a width of 0 in the icon picker. If I edit that to 24, they display. But that's about where my frontend skills end. I couldn't figure out where this is supposed to be set or why it's not working.

@masto is the width 0 on Chrome as well?

**Comment by masto** [comment]
> @masto is the width 0 on Chrome as well?

@menahishayan No, it seems correct in Chrome.

<img width="1655" alt="Screen Shot 2021-11-21 at 2 33 01 PM" src="https://user-images.githubusercontent.com/645516/142776360-833f41c4-ef35-4256-9745-943ccb90359d.png">

**Comment by menahishayan** [comment]
I've released a minor update. Please try updating and refreshing your frontend cache. Let me know if its resolved.

**Comment by mkgreco** [comment]
This update fixed the issue for me
