### ISSUE TITLE
Coloured Icons

### ISSUE THREAD

**Issue by drthanwho** [menahishayan/HomeAssistant-Cupertino-Icons#6]
Just a clarification I'm confused about. Is it only some icons that also exist in colour? From the readme it sounds like every single icon would also have a coloured version. But most icon I try to use they don't show with colour when I add #fullcolor at the end. 

And if only some are available anyway to see which ones those are? The apple's application is only for iOS and I don't have any devices

**Comment by menahishayan** [comment]
You can have a look at `./custom_components/cupertino/data/ios/` in this repo to view all the SVG icons. You'll be able to distinguish the colored and regular icons there.

**Comment by ElVit** [comment]
I had the same problem and found this solution with VS Code:
1. In VS Code install the extension "Native SVG Preview"
2. Add settings in VS Code `settings.js` so the preview is opend by default
`"workbench.editorAssociations": { "*.svg": "svgPreview.previewEditor" }`
3. Clone this repo and open it in VS Code
4. Search for `multicolor` to find all colored files
