### ISSUE TITLE
Integration not in "Add Integration" menu

### ISSUE THREAD

**Issue by Shadewing666** [menahishayan/HomeAssistant-Cupertino-Icons#7]
As the title says, the integration does not appear in the "Add Integration" menu in Home Assistant.

I had Cupertino Icons installed before the switch from frontend to integration but followed the instructions when I saw the Breaking Changes note in the update. Uninstall Cupertino, remove repo, add repo as integration type, install Cupertino, restart HA.

I have now also uninstalled Cupertino again, restarted HA, installed Cupertino, restarted again, and the integration still does not appear in the menu.

**Comment by YMGV** [comment]
Try to refresh the browser

**Comment by Shadewing666** [comment]
I had tried that but I just figured out the problem, searching for 'icon' does not return the Cupertino integration for some reason. Searching 'cup' does.

That seems like it would be a Home Assistant frontend issue though.

Working now.
