### ISSUE TITLE
repository structure non compliant

### ISSUE THREAD

**Issue by Gast0n87** [menahishayan/HomeAssistant-Cupertino-Icons#8]
Please update the structure to make it compliant with the latest version of home assistant.
I'm getting this message when I try to add your repo to my session:

"Repository structure for v3.0.2 is not compliant"

Thank you

**Comment by menahishayan** [comment]
What’s your HA and HACS version?

**Comment by Gast0n87** [comment]
It was a fresh install so I was running the latest HA and HACS versions. That said, my RPI4 crashed (has to do with HACS and github from the log file) and I'm forced to do a fresh install (won't have time to do that until this weekend). I'll get back to you once I do the install to see if I still get the same error.

**Comment by Gast0n87** [comment]
I did a fresh install and I'm still getting the same error. I'm running:
- HACS v1.20.0
        Frontend version: 20211231144850

- Home Assistant 2021.12.10
             Version	core-2021.12.10

When I try to add this repository I get the following message still "Repository structure for v3.0.2 is not compliant"

**Comment by Plymo-Kenny** [comment]
same here, fresh install aswel...

**Comment by menahishayan** [comment]
Closing since @KennyHec's response seems appropriate.
